travis:
  secure:
    BINSTAR_TOKEN: asowdAoCbCqmOpCCSCp2SQnwD7udxAzW0sRIt6mmv9Qgtwkm+jsAIXLyl5YmdnXs4iJ0Ce1ZcbW8ODUXciaMJDflDIrlwBlPv0G1U6aJkDwCbceN6w/jUIBNTV3jOFikJrhbB4A+7b9U8Y8xUa3yqQzu89hJdEsEfOfOG2O/6kbny2XvG8r+3TijBtpJGPPDH83XZnOtHPY0AsKXEvvjL2lGYZQiZBt8owmZFmD3/FBB/SIBgz6IYFf5ZMF9N91IErQvuI9CyTn1kWhwqKDAxiV0ZmItOMVR4ob9O4F7kIAmgT8rSHNrFXx+YjsP7xH45W0VOy5xt3mse+rZp9dLtvHx4KvyhozNc5ZNtp5y9Xc8LGQk5yCY7CxmEvKOA1NRa/4uksKsDK4vRlK66TrIfLD+lnSiynYPDrjuIIOb1cdHkcWrTcvfMItkwNnvZD1XM+kbwTGYtbZdAZtRVm1CBuEl296H2DCRjn0UK3uoL7xNFCtXypbgVV6wdsMKF2lxbED0H0CD1bmVWwu3agp1iEfnC357XIhWcC95tcEob6jUBc6dRhYTdswGPDQ105Mxl7OH1Hjy5TfntH4gEUOg0Bx7U3kjwRoBZSu8mCal0YFMBNjDGDNVHsZJQVNTV73Rvw5+OaqmUdeNYWjKgItmypjXdCl6j9UQrbNSzIwsjUc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
