travis:
  secure:
    BINSTAR_TOKEN: X6vzHeBUk5XMmx/SLpMyU0GkFGgL5+kCqQU7MIoKXb07vm0uIj2bipo/VGCgz9qxFL3WuUgnYDeJTY+N7PDTHpbFkMHoyPFI4XmGF+Zi5CvQoEFBrqqXYtl244dtd/TGlj9eJd1q7Du2ncd0hAJqw+xhGfAZGvnA9sR/x2p9ChDZQdssLg4paJr0UsZU2scrxOPiQ+3uq2uf1KddoUGhMGsrMkehuoPL6cEQy198oSZJaCQ6qUUImJi33dtV3U2KW00TXxKJaZx5Pi1/a2+yMJGRu9ILPMdafKF1BIvqivAVxtXVXkLRyrEmEpi57s4L0U0tci/bCnvgUAMFLgFvR9dgq1Orq9HRoHsas2Hg9GJfvEGzZzcRT9XF3sQ3D2BrmyykIA9lX/0FbX4VDkDAYgPEcyg2xyn1qdpZw9cbt7INKHatNTv8fZojpICE9egjV+AbAXDq/mMqCRtxrTlulVflV3DRLh5WTKUgp589I3VFaFDveuOqV0b//ZzGDpvEomB75FBFGnglPKP64WmxvzbDO3c9EDMDOOzjzNxlahrYMjA6RjDqzbq/u3SaKZGqvBcQ1Vyo2qp7hAPzOen2k0UieRe/zaIf2OpC/WrBdaJneGaxjEKDA6NucNJB94tGAGHpRXgGzJGamfRTXdbIT6eWvhKYp33vT/xVG1UwM9Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
